# https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch
dist: trusty
group: deprecated-2017Q4

sudo: required

cache:
  directories:
    - $HOME/.stack

before_install:
  # Download and unpack the stack executable
  - sudo rm /etc/apt/sources.list.d/mongodb-3.2.list
  - mkdir -p ${HOME}/.local/bin
  - export PATH=${HOME}/.local/bin:${PATH}
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ${HOME}/.local/bin '*/stack'
  - stack --version
  - stack setup

  # Install Z3
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:hvr/z3 -y > /dev/null; sudo apt-key -qq update /dev/null; sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq install z3 -y --force-yes; fi

addons:
  apt:
    sources:
    - hvr-ghc


jobs: 
  include: 
    - stage: verify toLabeled 
      script:
        - cd POPL19/
        - stack install
        - stack --skip-ghc-check test lmonad-lh:toLabeled

    - stage: verify all 
      script:
        - cd POPL19/
        - stack install
        - stack --skip-ghc-check test lmonad-lh:all

    - stage: verify update 
      script:
        - cd POPL19/
        - stack install
        - stack --skip-ghc-check test lmonad-lh:update

    - stage: verify select 
      script:
        - cd POPL19/
        - stack install
        - stack --skip-ghc-check test lmonad-lh:update

    - stage: verify delete 
      script:
        - cd POPL19/
        - stack install
        - stack --skip-ghc-check test lmonad-lh:delete

    - stage: verify insert 
      script:
        - cd POPL19/
        - stack install
        - stack --skip-ghc-check test lmonad-lh:insert
        

