resolver: nightly-2017-10-06

packages:
- 'src'

- location:
    git: https://github.com/ucsd-progsys/liquid-fixpoint.git
    commit: 6550be2226ff3a87cade9a64c215142dfefd1f3f

- location:
    git: https://github.com/ucsd-progsys/liquidhaskell.git
    commit: c607f625849f90cb6ef472f198e8fc96d6e9b69b


extra-deps:
- csv-table-0.1.0.1
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- intern-0.9.1.4
- located-base-0.1.1.1

flags:
  liquidhaskell:
    devel: true

extra-package-dbs: []
