# resolver: nightly-2017-10-06
resolver: lts-10.0

packages:
- '.'

- location:
    git: https://github.com/ucsd-progsys/liquid-fixpoint.git
    commit: b46761cd00552da6dec3e7bd4dd3161cd15ef3d6

- location:
    git: https://github.com/ucsd-progsys/liquidhaskell.git
    commit: 82f5baa2e8e9eb70171d9cd49bde4297e94c2029


extra-deps:
- csv-table-0.1.0.1
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- intern-0.9.1.4
- located-base-0.1.1.1
- liquidhaskell-0.8.2.2
- liquid-fixpoint-0.7.0.6

extra-package-dbs: []
