# resolver: nightly-2017-10-06
resolver: lts-10.0

packages:
- '.'

- location:
    git: https://github.com/ucsd-progsys/liquid-fixpoint.git
    commit: e14564a1fdca826944eeadea114bff750fc4a64d

- location:
    git: https://github.com/ucsd-progsys/liquidhaskell.git
    commit: 9f30411db5b8363e41210dc7a8dc22444474b246


extra-deps:
- csv-table-0.1.0.1
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- intern-0.9.1.4
- located-base-0.1.1.1
- liquidhaskell-0.8.2.2
- liquid-fixpoint-0.7.0.6

extra-package-dbs: []
