resolver: lts-12.3

packages:
- '.'


extra-deps:
- csv-table-0.1.0.1
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- located-base-0.1.1.1
- text-format-0.3.2
- intern-0.9.2

- git: https://github.com/ucsd-progsys/liquid-fixpoint
  commit: 52bb642efcc8bb44bd0d9d5ae4e21e5a533e652a

- git: https://github.com/ucsd-progsys/liquidhaskell
  commit: b6bbb6ca65a2a0cb405e56d8e29470c9f0302037

extra-package-dbs: []
allow-newer: true