resolver: lts-8.9

packages:
- 'src'

- location:
    git: https://github.com/ucsd-progsys/liquid-fixpoint.git
    commit: 138184a41dc73fec45393a980240e573c028fee3

- location:
    git: https://github.com/ucsd-progsys/liquidhaskell.git
    commit: fcb687b0482eacb36ce29012d8bc5ea4d7d4211b


extra-deps:
- aeson-0.11.3.0
- csv-table-0.1.0.1
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- intern-0.9.1.4
- located-base-0.1.1.0

flags:
  liquidhaskell:
    devel: true

extra-package-dbs: []
